### ISSUE TITLE
<video> elements are clipped on monitors that don't match the aspect ratio

### ISSUE THREAD

**Issue by Enteleform** [remotesynth/certifiedfreshevents#45]
It seems like this can be fixed with
```css
video{
  object-fit: contain;
}
```

![VideoFix](https://github.com/remotesynth/certifiedfreshevents/assets/10906415/d5a274e9-578b-4e98-b3eb-c086815ebbb7)
